gas_adjustment = 1.5
gas_prices = "0.00125ukuji"
enable_server = true
enable_voter = true

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[deviation_thresholds]]
base = "USDT"
threshold = "2"

# Stable coins
# -----------------------------------------------------------------------------

[[currency_pairs]]
base = "USDT"
quote = "USD"
providers = ["coinbase", "kraken", "crypto", "gate", "binanceus"]

# USD
# -----------------------------------------------------------------------------

[[currency_pairs]]
base = "ATOM"
quote = "USD"
providers = ["coinbase", "kraken"]

[[currency_pairs]]
base = "BTC"
quote = "USD"
providers = ["coinbase", "kraken", "crypto", "bitfinex"]

[[currency_pairs]]
base = "DOT"
quote = "USD"
providers = ["coinbase", "kraken", "bitfinex"]

[[currency_pairs]]
base = "ETH"
quote = "USD"
providers = ["coinbase", "kraken", "crypto", "bitfinex"]

[[currency_pairs]]
base = "LUNA"
quote = "USD"
providers = ["kraken", "crypto", "bitfinex"]

# USDT
# -----------------------------------------------------------------------------

[[currency_pairs]]
base = "ATOM"
quote = "USDT"
providers = ["binance", "mexc", "huobi", "okx", "crypto", "gate", "bitget", "bybit", "hitbtc", "kucoin", "bitforex", "poloniex", "phemex", "lbank"]

[[currency_pairs]]
base = "BNB"
quote = "USDT"
providers = ["binance", "mexc", "huobi", "okx", "gate", "bitget", "bybit", "hitbtc", "kucoin", "poloniex", "phemex", "lbank"]

[[currency_pairs]]
base = "BTC"
quote = "USDT"
providers = ["binance", "mexc", "huobi", "okx", "gate", "bitget", "bybit", "hitbtc", "kucoin", "bitforex", "poloniex", "phemex", "lbank"]

[[currency_pairs]]
base = "DOT"
quote = "USDT"
providers = ["binance", "mexc", "huobi", "okx", "crypto", "gate", "bitget", "bybit", "hitbtc", "kucoin", "bitforex", "poloniex", "phemex", "lbank"]

[[currency_pairs]]
base = "ETH"
quote = "USDT"
providers = ["binance", "mexc", "huobi", "okx", "gate", "bitget", "bybit", "hitbtc", "kucoin", "bitforex", "poloniex", "phemex", "lbank"]

[[currency_pairs]]
base = "LUNA"
quote = "USDT"
providers = ["binance", "mexc", "huobi", "okx", "gate", "bitget", "bybit", "hitbtc", "kucoin", "bitforex", "poloniex", "phemex", "lbank"]

# BTC
# -----------------------------------------------------------------------------

[[currency_pairs]]
base = "BNB"
quote = "BTC"
providers = ["bitforex"]

# -----------------------------------------------------------------------------

[account]
address = "kujira..."
chain_id = "kaiyo-1"
validator = "kujiravaloper..."
prefix = "kujira"
# Optional
fee_granter = "kujira..."

[keyring]
backend = "file"
dir = "/home/<user>/.kujira"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable_hostname = true
enable_hostname_label = true
enable_service_label = true
enabled = true
global_labels = [["chain-id", "kaiyo-1"]]
service_name = "price-feeder"
type = "prometheus"

[[provider_endpoints]]
name = "binance"
rest = "https://api1.binance.com"
websocket = "stream.binance.com:9443"

[[healthchecks]]
url = "https://hc-ping.com/HEALTHCHECK-UUID"
